export const commonSoftwareEngineeringRoles = [
  "Software Engineer",
  "Software Developer",
  "Frontend Developer",
  "Backend Developer",
  "Blockchain Developer",
  "Algorithm Design Engineer",
  "Full-stack Developer",
  "Mobile App Developer (iOS/Android)",
  "Web Developer",
  "DevOps Engineer",
  "Systems Engineer",
  "Quality Assurance (QA) Engineer",
  "Test Automation Engineer",
  "Software Architect",
  "Database Administrator (DBA)",
  "Data Engineer",
  "Machine Learning Engineer",
  "Artificial Intelligence Engineer",
  "Game Developer",
  "Embedded Systems Engineer",
  "Cloud Engineer",
  "Security Engineer",
  "UI/UX Designer",
  "Technical Lead",
  "Project Manager (with technical background)",
  "Release Engineer",
  "Build Engineer",
];

export const commonComputerScienceSkills = [
  "React",
  "Angular",
  "Vue.js",
  "React Native",
  "Flutter",
  "Solidity",
  "Node.js",
  "Express.js",
  "Jest",
  "Mocha",
  "Selenium",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Git",
  "SVN",
  "SQL",
  "MongoDB",
  "AWS",
  "Azure",
  "Google Cloud",
  "Bootstrap",
  "Material UI",
  "Tailwind CSS",
  "Spring Boot",
  "Hibernate",
  "ASP.NET",
  "Ruby on Rails",
  "Flask",
  "Django",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Scikit-learn",
  "Unity",
  "Unreal Engine",
  "Arduino",
  "Raspberry Pi",
  "Redux",
  "RxJS",
  "jQuery",
  "Webpack",
  "Babel",
  "Gulp",
  "Grunt",
  "Cypress",
  "Selenium WebDriver",
  "JUnit",
  "Cucumber",
  "Postman",
  "Swagger",
  "Terraform",
  "Ansible",
  "Puppet",
  "Chef",
  "Prometheus",
  "Grafana",
  "ELK Stack",
  "Splunk",
  "Firebase",
  "Heroku",
  "Netlify",
  "Jira",
  "Confluence",
  "Slack",
  "Trello",
  "Asana",
  "Zendesk",
  "Matplotlib",
  "Seaborn",
  "Plotly",
  "Highcharts",
  "D3.js",
  "Three.js",
  "OpenGL",
  "DirectX",
];
