import {
  AlertCircle,
  Archive,
  ArchiveX,
  File,
  Inbox,
  MessagesSquare,
  ShoppingCart,
  Users2,
  CheckCircle,
  MessageCircleMore,
  Pin,
  Circle,
} from "lucide-react";

export const navoption = {
  bar: [
    {
      title: "Inbox",
      label: "128",
      icon: Inbox,
      variant: "default",
      href: "inbox",
    },
    {
      title: "Tasks",
      label: "",
      icon: CheckCircle,
      variant: "ghost",
      href: "tasks",
    },
    {
      title: "Messages",
      label: "27",
      icon: MessageCircleMore,
      variant: "ghost",
      href: "messages",
    },
    {
      title: "Notes",
      label: "",
      icon: Pin,
      variant: "ghost",
      href: "notes",
    },
    {
      title: "Drafts",
      label: "9",
      icon: File,
      variant: "ghost",
      href: "drafts",
    },
    {
      title: "Junk",
      label: "23",
      icon: ArchiveX,
      variant: "ghost",
      href: "junk",
    },
    {
      title: "Spaces",
      label: "",
      icon: Circle,
      variant: "ghost",
      href: "spaces",
    },
    {
      title: "Social",
      label: "972",
      icon: Users2,
      variant: "ghost",
      href: "social",
    },
    {
      title: "Updates",
      label: "342",
      icon: AlertCircle,
      variant: "ghost",
      href: "updates",
    },
    {
      title: "Forums",
      label: "128",
      icon: MessagesSquare,
      variant: "ghost",
      href: "forums",
    },
    {
      title: "Shopping",
      label: "8",
      icon: ShoppingCart,
      variant: "ghost",
      href: "shopping",
    },
    {
      title: "Promotions",
      label: "21",
      icon: Archive,
      variant: "ghost",
      href: "promotions",
    },
  ],
};
